# Author: Santosh Pandit
# Purpose: Customisable server blocks
# Note: Ensure correct files exist in the /home/local path

# Disallow http traffic on IPv4 and IPv6 and unknown servers
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	return 444;
}

# Disallow https traffic on IPv4 and IPv6 and unknown servers
server {
	listen 443 ssl default_server;
	listen [::]:443 ssl default_server;
	ssl_reject_handshake on;
	return 444;
}

# Redirect from http to https for the named server
server {
    listen 80;
    listen [::]:80;
    include /home/local/local_server_name.txt;

    location /.well-known/acme-challenge/ { root /var/www/letsencrypt; }
    location / { return 301 https://$host$request_uri; }
}

# Main server using https on tcp and udp port 443
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic reuseport;
    listen [::]:443 quic reuseport;

    include /home/local/local_server_name.txt;
    root /var/www/linuxcore;

    http2 on;
    http3 on;
    http3_hq on; # Temporarily enable QUIC interoperability tests
    quic_bpf on; # Temporarily enable QUIC migration tests
    quic_retry on; # Temporarily enable QUIC address validation tests
    ssl_early_data on; # Temporarily enable 0-RTT

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers EECDH+CHACHA20:EECDH+AESGCM+AES256;

    ssl_dhparam /etc/nginx/dhparam.pem;
 
    ssl_conf_command Ciphersuites TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384;
    ssl_conf_command Options ServerPreference,PrioritizeChaCha,NoRenegotiation,NoResumptionOnRenegotiation;
 
    ssl_prefer_server_ciphers on;
    ssl_ecdh_curve secp384r1;

    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_session_tickets off;

    ssl_certificate /etc/letsencrypt/live/linuxcore.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/linuxcore.cloud/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/linuxcore.cloud/chain.pem;

    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 1.1.1.1;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Referrer-Policy "no-referrer";
    add_header Content-Security-Policy "default-src 'none'; style-src 'sha256-q851zP+jk6l3BIrOOtKjLDmdR1NlnxNlCUrw3/c3Pbk='; img-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self';";
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=(), fullscreen=(), payment=()";
    add_header Cross-Origin-Embedder-Policy "require-corp";
    add_header Cross-Origin-Opener-Policy "same-origin";
    add_header Cross-Origin-Resource-Policy "same-origin";
#    add_header Set-Cookie "linuxcore.cloud=; HttpOnly; SameSite=Strict; Secure; Path=/";

    add_header Alt-Svc 'h3=":443"; ma=86400';

    # Location for handling requests
    location / {
        try_files $uri.html $uri /index.html =444;
    }
}
