#SPDX-License-Identifier: MIT-0
---
# tasks file for webserver
- name: Update apt cache initially
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install extrepo
  ansible.builtin.apt:
    name: extrepo
    state: present
  become: yes

- name: Enable n.wtf repository
  ansible.builtin.command: extrepo enable n.wtf
  become: yes
  changed_when: true

- name: Update apt cache after enabling repository
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install nginx-extras
  ansible.builtin.apt:
    name: nginx-extras
    state: present
  become: yes

- name: Copy nginx.conf
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Reload nginx

- name: Ensure conf.d directory exists
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Copy badagent.conf
  ansible.builtin.copy:
    src: badagent.conf
    dest: /etc/nginx/conf.d/badagent.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Reload nginx

- name: Copy loggable.conf
  ansible.builtin.copy:
    src: loggable.conf
    dest: /etc/nginx/conf.d/loggable.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Reload nginx

- name: Copy geoblocking.conf
  ansible.builtin.copy:
    src: geoblocking.conf
    dest: /etc/nginx/conf.d/geoblocking.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Reload nginx

- name: Install PHP 8.4-FPM prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - apt-transport-https
      - lsb-release
    state: present
    update_cache: yes
  become: yes

- name: Add PHP repository GPG key
  ansible.builtin.get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/php.gpg
    mode: '0644'
  become: yes

- name: Add PHP repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present
    filename: php
  become: yes

- name: Update apt cache after adding PHP repository
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install php8.4-fpm
  ansible.builtin.apt:
    name: php8.4-fpm
    state: present
  become: yes

- name: Ensure php8.4-fpm service is enabled and running
  ansible.builtin.service:
    name: php8.4-fpm
    state: started
    enabled: yes
  become: yes

- name: Ensure nginx service is enabled and running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  become: yes
